scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['service.127.0.0.1.xip.io:8080']
    tls_config:
      insecure_skip_verify: true