spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:./misc/config/,file:./misc/config/{application}/,file:./misc/config/{application}/{profile}/,file:./misc/config/{application}/{profile}/{label}