version: '3'

services:
  mysql:
    image: mysql:8
    volumes:
      - ./configuration/:/etc/mysql/conf.d
      - ./scripts/:/scripts/
      - mysql-data:/var/lib/mysql
      - mysql-log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogbitix
    entrypoint: ''
    command: bash -c "chown -R mysql:mysql /var/log/mysql && exec /entrypoint.sh mysqld"

volumes:
  mysql-data:
  mysql-log: