version: '3'

dotenv: ['.env']

tasks:
  build:
    cmds:
      - ../gradlew ${GRADLE_OPTIONS} build

  schedule:
    deps:
      - task: schedule:jacoco

  run:
    cmds:
      - ../gradlew ${GRADLE_OPTIONS} run

  setup:install:
    cmds:
      - echo "setup:install"

  build:check:
    deps:
      - task: build:test
      - task: build:pmd
      - task: build:checkstyle
      - task: build:spotbugs

  build:test:
    cmds:
      - ../gradlew ${GRADLE_OPTIONS} test

  build:pmd:
    cmds:
      - ../gradlew ${GRADLE_OPTIONS} pmdMain pmdTest

  build:checkstyle:
    cmds:
      - ../gradlew ${GRADLE_OPTIONS} checkstyleMain checkstyleTest

  build:spotbugs:
    cmds:
      - ../gradlew ${GRADLE_OPTIONS} spotBugMain spotBugTest

  build:sonar:
    cmds:
      - ../gradlew ${GRADLE_OPTIONS} -Dorg.gradle.project.sonarToken="${SONAR_TOKEN}" build jacocoTestReport sonar

  build:version:
    cmds:
      - ../gradlew -q version

  build:assemble:
    cmds:
      - ../gradlew ${GRADLE_OPTIONS} clean assemble

  build:publish:
    cmds:
      - echo "build:publish"

  build:assemble-image:
    cmds:
      - ../gradlew ${GRADLE_OPTIONS} bootBuildImage

  schedule:jacoco:
    cmds:
      - ../gradlew ${GRADLE_OPTIONS} test jacocoTestReport

