FROM picodotdev/base:1.0
MAINTAINER picodotdev <pico.dev@gmail.com>

ENV HOME /root

RUN apt-get install -y mysql-server mysql-client

ADD my.cnf /etc/mysql/my.cnf
RUN mkdir /etc/service/mysql
ADD mysql /etc/service/mysql/run
RUN chmod +x /etc/service/mysql/run

RUN rm -R /var/lib/mysql && \
	mkdir /var/lib/mysql && \
    mkdir /mnt/keys

VOLUME ["/var/lib/mysql", "/mnt/keys"]

RUN apt-get clean && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 22 3306

CMD ["/sbin/my_init"]