version: "3"
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    volumes:
      - data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_NODENAME=rabbitmq

volumes:
  data:
