...
System.out.println("Message with argument (en): " + MessageFormat.format(enBundle.getString("message_0"), "picodotdev"));
System.out.println("Message with argument (es): " + MessageFormat.format(esBundle.getString("message_0"), "picodotdev"));
...