version: '3'
services:
  weblate:
    ports:
      - 80:8080
    environment:
      WEBLATE_SITE_DOMAIN: weblate.127.0.0.1.xip.io
      WEBLATE_ADMIN_EMAIL: weblate.admin@weblate.127.0.0.1.xip.io
      WEBLATE_ADMIN_PASSWORD: password

