name: setup-gradle
description: 'Setup Gradle'

runs:
  using: 'composite'
  steps:
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: false
    - name: Configure Task
      shell: bash
      run: |-
        echo "GRADLE_OPTIONS=-console plain" >> .env
