name: setup-task
description: 'Setup Task'

inputs:
  task-version:
    default: '3.x'

runs:
  using: "composite"
  steps:
    - name: Setup Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
