$ curl http://nginx-weighted.127.0.0.1.sslip.io:8080/
<!DOCTYPE html>
...
<title>Welcome to nginx (nginx-1)!</title>
...
$ curl http://nginx-weighted.127.0.0.1.sslip.io:8080/
<!DOCTYPE html>
...
<title>Welcome to nginx (nginx-1)!</title>
...
$ curl http://nginx-weighted.127.0.0.1.sslip.io:8080/
<!DOCTYPE html>
...
<title>Welcome to nginx (nginx-1)!</title>
...
$ curl http://nginx-weighted.127.0.0.1.sslip.io:8080/
<!DOCTYPE html>
...
<title>Welcome to nginx (nginx-2)!</title>
...
$ curl http://nginx-weighted.127.0.0.1.sslip.io:8080/
<!DOCTYPE html>
...
<title>Welcome to nginx (nginx-1)!</title>
...