# See https://docs.flagsmith.com/deployment/docker for more information on running Flagsmith in Docker
x-flagsmith-env: &flagsmith-env
  DATABASE_URL: postgresql://postgres:password@postgres:5432/flagsmith
  USE_POSTGRES_FOR_ANALYTICS: 'true'
  ENVIRONMENT: production
  DJANGO_ALLOWED_HOSTS: '*'
  FLAGSMITH_DOMAIN: localhost:8000
  DJANGO_SECRET_KEY: secret

  TASK_RUN_METHOD: TASK_PROCESSOR # other options are: SYNCHRONOUSLY, SEPARATE_THREAD (default)
  PROMETHEUS_ENABLED: 'true'

volumes:
  pgdata:

services:
  postgres:
    image: postgres:15.5-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flagsmith
    container_name: flagsmith_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d flagsmith -U postgres']
      interval: 2s
      timeout: 2s
      retries: 20
      start_period: 20s

  flagsmith:
    image: docker.flagsmith.com/flagsmith/flagsmith:latest
    command:
      - serve
    environment:
      <<: *flagsmith-env
    ports:
      - 8000:8000
    depends_on:
      flagsmith-migrate-db:
        condition: service_completed_successfully

  flagsmith-task-processor:
    image: docker.flagsmith.com/flagsmith/flagsmith:latest
    environment:
      <<: *flagsmith-env
    ports:
      - 8001:8000
    depends_on:
      flagsmith-migrate-db:
        condition: service_completed_successfully
    command: run-task-processor

  flagsmith-migrate-db:
    image: docker.flagsmith.com/flagsmith/flagsmith:latest
    command:
      - migrate
    environment:
      <<: *flagsmith-env
    healthcheck:
      disable: true
    depends_on:
      postgres:
        condition: service_healthy
