spring:
  cloud:
    function:
      bindings:
        uppercase-in-0: uppercase-in
        uppercase-out-0: uppercase-out
        logger-in-0: logger-in
    stream:
      bindings:
        uppercase-in:
          destination: message
          group: uppercase-function
        uppercase-out:
          destination: message-uppercase
        logger-in:
          destination: message-uppercase
          group: logger-consumer