spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            security:
              protocol: SASL_SSL
            sasl:
              mechanism: PLAIN
              jaas:
                config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${username}" password="${password}";
        default:
          consumer:
            property: value
          producer:
            property: value