/*
 * Catalog
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.picodotdev.catalog.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.picodotdev.catalog.client.model.ClientCategory;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ClientEvent
 */
@JsonPropertyOrder({
  ClientEvent.JSON_PROPERTY_ID,
  ClientEvent.JSON_PROPERTY_NAME,
  ClientEvent.JSON_PROPERTY_STATUS,
  ClientEvent.JSON_PROPERTY_LOCALE,
  ClientEvent.JSON_PROPERTY_DATE,
  ClientEvent.JSON_PROPERTY_TIMEZONE,
  ClientEvent.JSON_PROPERTY_URI,
  ClientEvent.JSON_PROPERTY_SEO_U_R_I,
  ClientEvent.JSON_PROPERTY_CATEGORIES
})
@JsonTypeName("Event")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-18T12:11:21.115053824+02:00[Europe/Madrid]", comments = "Generator version: 7.12.0")
public class ClientEvent {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_LOCALE = "locale";
  @jakarta.annotation.Nullable
  private String locale;

  public static final String JSON_PROPERTY_DATE = "date";
  @jakarta.annotation.Nullable
  private String date;

  public static final String JSON_PROPERTY_TIMEZONE = "timezone";
  @jakarta.annotation.Nullable
  private String timezone;

  public static final String JSON_PROPERTY_URI = "uri";
  @jakarta.annotation.Nullable
  private String uri;

  public static final String JSON_PROPERTY_SEO_U_R_I = "seoURI";
  @jakarta.annotation.Nullable
  private String seoURI;

  public static final String JSON_PROPERTY_CATEGORIES = "categories";
  @jakarta.annotation.Nullable
  private List<ClientCategory> categories = new ArrayList<>();

  public ClientEvent() {
  }

  public ClientEvent id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }

  public ClientEvent name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public ClientEvent status(@jakarta.annotation.Nullable String status) {
    
    this.status = status;
    return this;
  }

  ...
}

