---
- hosts: devbox
    - name: start docker service
      service: name=docker state=started
      sudo: true
   
    - name: build docker images
      docker_image: name="{{ item.name }}" tag="{{ item.tag }}" state="present" path={{ item.path }}
      with_items:
      - { name: "picodotdev/base", tag: "1.0", path: "../docker/base" }
      - { name: "picodotdev/mysql", tag: "1.0", path: "../docker/mysql" }
      - { name: "picodotdev/redis", tag: "1.0", path: "../docker/redis" }
      - { name: "picodotdev/apps", tag: "1.0", path: "../docker/apps" }