# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "ubuntu" do |instance|
      instance.vm.box = "ubuntu/jammy64"
      instance.vm.network "private_network", ip: "192.168.56.10"
      instance.vm.synced_folder ".", "/home/vagrant/ConsulServiceMesh/"

      instance.vm.provider :virtualbox do |vb|
        vb.name = "Ubuntu 22.04 (Vagrant)"
        vb.memory = "4096"

        instance.vm.provision "shell", inline: $consul_role_script
      end
    end

    $consul_role_script = <<-SCRIPT
      echo "Updating..."
      sudo apt-get update
      sudo apt-get upgrade

      echo "Installing Docker..."
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker.gpg
      echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      sudo apt-get update && sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin && sudo systemctl enable docker.service
      sudo usermod -aG docker vagrant
    SCRIPT
  end
  