version: '3.4'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab'
        nginx['ssl_certificate'] = '/etc/gitlab/ssl/gitlab.crt'
        nginx['ssl_certificate_key'] = '/etc/gitlab/ssl/gitlab.key'
    ports:
      - '8022:22'
      - '8080:80'
      - '8443:443'
    volumes:
      - 'gitlab-config-volume:/etc/gitlab'
      - 'gitlab-log-volume:/var/log/gitlab'
      - 'gitlab-data-volume:/var/opt/gitlab'
      - './docker-volumes/gitlab/ssl:/etc/gitlab/ssl'

volumes:
  gitlab-config-volume:
  gitlab-log-volume:
  gitlab-data-volume:
