name: setup-java
description: 'Setup Java'

inputs:
  java-version:
    type: string
    required: false
    default: '21'
  java-distribution:
    type: string
    required: false
    default: 'temurin'
  cache:
    type: string
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup JDK ${{ inputs.java-version }}-${{ inputs.java-distribution }}
      uses: actions/setup-java@v4
      if: ${{ inputs.cache == null || inputs.cache == '' }}
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
        cache: ${{ inputs.cache }}