name: setup-gradle
description: 'Setup Semantic Release'

inputs:
  node-version:
    type: string
    default: '20'

runs:
  using: "composite"
  steps:
    - name: Setup semantic release
      uses: ./.github/actions/setup-node
      with:
        node-version: ${{ inputs.node-version }}
