version: '3'

services:
  postgres:
    image: postgres:11
    volumes:
      - ./configuration/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./scripts/:/scripts/
      - postgres-data:/var/lib/postgresql/data
      - postgres-log:/var/log/postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogbitix
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

volumes:
  postgres-data:
  postgres-log: