name: main

on:
  push:
    branches:
      - main
      - master
  merge_group:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Reference to checkout'
        required: true
        type: string

jobs:
  build:
    name: build
    uses: ./.github/workflows/build-check-task.yml
    with:
      ref: ${{ inputs.ref || github.head_ref || github.ref_name }}
      context-directory: ./gradle-app
      setup-java-version: ${{ vars.JAVA_VERSION }}
      setup-gradle: true
      setup-task: true
      setup-docker: true
      check-tasks: |
        ["build:test", "build:pmd", "build:checkstyle", "build:spotbugs", "build:sonar"]
      check-tasks-reports: |
        {
          "build:test": "./gradle-app/build/reports/tests",
          "build:pmd": "./gradle-app/build/reports/pmd",
          "build:checkstyle": "./gradle-app/build/reports/checkstyle",
          "build:spotbugs": "./gradle-app/build/spotbugs"
        }
    secrets:
      workflows-token: ${{ secrets.GH_CI_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
  release:
    name: release
    uses: ./.github/workflows/build-release-dockerfile.yml
    needs: [build]
    with:
      ref: ${{ inputs.ref || github.head_ref || github.ref_name }}
      context-directory: ./gradle-app
      builder: gradle
      bump: patch
      setup-java-version: ${{ vars.JAVA_VERSION }}
      setup-gradle: true
      setup-task: true
      setup-docker: true
      artifact: ./gradle-app/build/distributions/platform-github-actions-workflows-*.zip
      artifact-name: platform-github-actions-workflows-gradle-app
      container-image-name: platform-github-actions-workflows
      artifact-dockerfile: ./gradle-app/miscellaneous/docker/Dockerfile
    secrets:
      workflows-token: ${{ secrets.GH_CI_TOKEN }}
      jira-token: ${{ secrets.JIRA_TOKEN }}
  deploy:
    name: deploy
    uses: ./.github/workflows/deploy-gke.yml
    needs: [release]
    with:
      ref: ${{ inputs.ref || github.head_ref || github.ref_name }}
      dry-run: true
      deployment-directory: ./gradle-app/miscellaneous/gke/development
      container-image-name: platform-github-actions-workflows
      environment: production
      release-outputs: ${{ toJSON(needs.release.outputs) }}
    secrets:
      workflows-token: ${{ secrets.GH_CI_TOKEN }}
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
