- hosts: devbox
  tasks:
    - name: start docker service
      service: name=docker state=started
      sudo: true

    - name: start mysql data docker container
      docker: image=busybox:latest name=picodotdev-mysql-data state=present volumes="/var/lib/mysql"
      register: mysql_data_container

    - name: start redis data docker container
      docker: image=busybox:latest name=picodotdev-redis-data state=present volumes="/var/lib/redis"
      register: redis_data_container

    - name: start mysql docker container
      docker: image=picodotdev/mysql:1.0 name=picodotdev-mysql state=running volumes_from=picodotdev-mysql-data hostname=mysql ports=3306:3306 command=/sbin/my_init
      register: mysql_container

    - name: start redis docker container
      docker: image=picodotdev/redis:1.0 name=picodotdev-redis state=running volumes_from=picodotdev-redis-data volumes="{{ keys_path }}:/mnt/keys" hostname=redis ports=6379:6379 command=/sbin/my_init
      register: redis_container

    - name: start apps docker container
      docker: image=picodotdev/apps:1.0 name=picodotdev-apps state=running volumes="{{ projects_path }}:/mnt/projects,{{ grails_path }}:/root/.grails,{{ gradle_path }}:/root/.gradle,{{ keys_path }}:/mnt/keys" hostname=apps ports=8080:8080,8443:8443 links=picodotdev-mysql:mysql,picodotdev-redis:redis command=/sbin/my_init
      register: apps_container

    - name: update hosts with containers ip address
      replace: dest=/etc/hosts regexp="^(\d+\.\d+\.\d+\.\d+)(\s+{{ item.host }})$" replace="{{ item.ip }}\2"
      sudo: true
      with_items:
      - { host: "mysql", ip: "{{ mysql_container['ansible_facts']['docker_containers'][0]['NetworkSettings']['IPAddress'] }}" }
      - { host: "redis", ip: "{{ redis_container['ansible_facts']['docker_containers'][0]['NetworkSettings']['IPAddress'] }}" }
      - { host: "apps", ip: "{{ apps_container['ansible_facts']['docker_containers'][0]['NetworkSettings']['IPAddress'] }}" }

    - name: display containers info
      debug: msg="info"
      with_items:
      - { name: "{{ mysql_container['ansible_facts']['docker_containers'][0]['Name'] }}", ip: "{{ mysql_container['ansible_facts']['docker_containers'][0]['NetworkSettings']['IPAddress'] }}", id: "{{ mysql_container['ansible_facts']['docker_containers'][0]['Id'] }}" }
      - { name: "{{ redis_container['ansible_facts']['docker_containers'][0]['Name'] }}", ip: "{{ redis_container['ansible_facts']['docker_containers'][0]['NetworkSettings']['IPAddress'] }}", id: "{{ redis_container['ansible_facts']['docker_containers'][0]['Id'] }}" }
      - { name: "{{ apps_container['ansible_facts']['docker_containers'][0]['Name'] }}", ip: "{{ apps_container['ansible_facts']['docker_containers'][0]['NetworkSettings']['IPAddress'] }}", id: "{{ apps_container['ansible_facts']['docker_containers'][0]['Id'] }}" }