server:
  port: ${port:8080}

spring:
  application:
    name: service
  profiles:
    active: cloud
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: '*'

config:
  key: value
